### ISSUE TITLE
Problem with gocart initialisation

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/gocart#14]
Sorry Dave!

When gocart starts to rattle through the old maps, we get this error:

```
lect all alerts missed while off-line.
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|========================================================================================================================================================================================================| 1.3k/1.3k (100.00%)         0s
EVENT: MS230406r detected at 2023-04-06T17:41:35.308 UTC
ALERT: PRELIMINARY reported at 2023-04-06T17:54:27 UTC (+12.86 mins)
FAR: 1 per 61251822.2 yrs
CLASSIFICATION: {'BNS': 1.0, 'NSBH': 0.0, 'BBH': 0.0, 'Terrestrial': 0.0}
PROPERTIES: {'HasNS': 1.0, 'HasRemnant': 1.0, 'HasMassGap': 0.0})


Traceback (most recent call last):
  File "/home/ligo/anaconda3/envs/gocart/bin/gocart", line 8, in <module>
    sys.exit(main())
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/gocart/cl_utils.py", line 155, in main
    parser = lvk(
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/gocart/parsers/lvk.py", line 156, in parse
    c = ascii(
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/gocart/convert/ascii.py", line 62, in __init__
    self.hdus, self.table = flatten_healpix_map(
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/gocart/commonutils/flatten_healpix_map.py", line 55, in flatten_healpix_map
    from ligo.skymap.bayestar import rasterize
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/ligo/skymap/bayestar/__init__.py", line 39, in <module>
    from .. import distance
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/ligo/skymap/distance.py", line 38, in <module>
    import healpy as hp
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/healpy/__init__.py", line 95, in <module>
    from .rotator import Rotator, vec2dir, dir2vec
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/healpy/rotator.py", line 36, in <module>
    SkyCoord(
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py", line 675, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/transformations.py", line 1479, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/transformations.py", line 1252, in __call__
    newrep = self._apply_transform(fromcoord, *params)
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/transformations.py", line 1174, in _apply_transform
    rep = rep.transform(matrix)
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 1399, in transform
    p = erfa_ufunc.rxp(matrix, self.get_xyz(xyz_axis=-1))
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 1351, in get_xyz
    return np.stack([self._x, self._y, self._z], axis=xyz_axis)
  File "<__array_function__ internals>", line 200, in stack
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/units/quantity.py", line 1683, in __array_function__
    return super().__array_function__(function, types, args, kwargs)
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/numpy/core/shape_base.py", line 471, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,
  File "<__array_function__ internals>", line 200, in concatenate
  File "/home/ligo/anaconda3/envs/gocart/lib/python3.9/site-packages/astropy/units/quantity.py", line 1688, in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
TypeError: concatenate() got an unexpected keyword argument 'dtype'
```

**Comment by thespacedoctor** [comment]
Can you do a `conda install astropy` please?

**Comment by thespacedoctor** [comment]
Fix it ... it actually needed a `conda install numpy`.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/3385557/230460233-6c274860-24fb-4f26-be64-791624e9409b.png">

**Comment by genghisken** [comment]
Interesting. Thanks. I had a very similar issue with numpy in my webserver code recently.
